version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
    networks: ["nats"]
    healthcheck:
      test: ["CMD", "nats", "-z", "nats://nats:4222"]
      interval: 5s
      timeout: 10s
      retries: 3
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://nats:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
    healthcheck:
      test: ["CMD", "nats", "-z", "nats://nats:4222"]
      interval: 5s
      timeout: 10s
      retries: 3
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://nats:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
    healthcheck:
      test: ["CMD", "nats", "-z", "nats://nats:4222"]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  nats:
    name: nats
